name: 'Setup Node.js and Install Dependencies'
description: 'Checks out the code, sets up Node.js, and installs dependencies using npm ci --force'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci --force
